# Workflow copied from: 
# https://github.com/freetonik/textpod/blob/bdeac83a64a6ad591528ba8dc08f8422c73ff0cb/.github/workflows/cd.yml
# https://rakhim.exotext.com/how-to-build-and-publish-multi-platform-rust-binaries

# For crates: create an API token at https://crates.io/settings/tokens add it as the CARGO_REGISTRY_TOKEN variable to your github secrets.
# For dockerhub: store DOCKERHUB_USERNAME and DOCKERHUB_TOKEN as secrets.

name: release

on:
  release:
    types:
    - created

jobs:
  linux_windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install Linux and Windows Cross Compilers
      run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32

    - name: Install rustup targets
      run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu

    - name: Build the executable
      run: cargo build --release --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu

    - name: Tar x86_64 binary
      run: tar -czvf discord_gpt-gnu-linux-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release discord_gpt

    - name: Zip windows binary
      run: zip -j discord_gpt-windows.zip target/x86_64-pc-windows-gnu/release/discord_gpt.exe

    - name: Generate SHA256 checksums
      run: |
        shasum -a 256 textpod-gnu-linux-x86_64.tar.gz > textpod-gnu-linux-x86_64.tar.gz.sha256
        shasum -a 256 textpod-windows.zip > textpod-windows.zip.sha256

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["discord_gpt-gnu-linux-x86_64.tar.gz", "discord_gpt-windows.zip", "discord_gpt-gnu-linux-x86_64.tar.gz.sha256", "discord_gpt-windows.zip.sha256"]'

  # crates:
  #   runs-on: ubuntu-latest
  #   needs: [linux_windows]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: stable
  #       override: true
  #   - uses: katyo/publish-crates@v2
  #     with:
  #       registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: crates
  #   steps:
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         tags: ashiven/discord-gpt:latest
